### PR TITLE
Fix create ticket endpoint

### PR DESCRIPTION
**Pull request by talvasconcelos**
I think this may solve the problem!

### CODE REVIEW

**Review by dni — APPROVED** [review]

**Review by callebtc — APPROVED** [review]
LGTM, good fix

**Comment by oren-z0** [comment]
@talvasconcelos What happens if the user creates lots of tickets and doesn't pay them? Is there any mechanism for deleting those records when the invoice expires? Are they reduced from the amount of tickets left?
I'm working on the https://github.com/oren-z0/bets4sats extension (forked from Events), and I'm trying to apply the latest fixes onto Bets4Sats.

**Comment by talvasconcelos** [comment]
hmmm... i think tickets don't get deleted! Let me look at how we can best implement that feature.

**Comment by talvasconcelos** [comment]
Ok, after reviewing the code, @oren-z0 , if the number of available tickets (sold tickets) is less than 1, you get an error page, saying all tickets have been sold. Apparently, only paid tickets are marked as sold. So even if someone creates multiple tickets, if they don't pay them, they don't count.

That being said, i think it's relevant to have some kind of "purge" of those unpaid tickets after a while, even to prevent spamming. I'm looking into how to do it, will keep you posted!

**Comment by oren-z0** [comment]
> Ok, after reviewing the code, @oren-z0 , if the number of available tickets (sold tickets) is less than 1, you get an error page, saying all tickets have been sold. 

But what if there was 1 ticket left, and 5 people create invoices (without paying them), wait for 1 minute, and then pay the invoices?
I didn't test this case, but from overviewing the code I think it can create strange situations. Tickets that haven't been paid yet *should* be deducted from the total amount - and then they should be purged as you said (and the amount of tickets left should be increased again).

And then you have the "DDOS" case where some a**hole creates a lot of tickets without paying them - just to keep the amount-of-tickets-left on zero... This can be solved with a captcha I guess...

**Pull request merged**
